default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: to_do_rails_development

test:
  <<: *default
  database: to_do_rails_test

production:
  <<: *default
  database: to_do_rails_production
  username: to_do_rails
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
